### ISSUE TITLE
License of Repository

### ISSUE THREAD

**Issue by jalused** [wanghao2020/FiveChess#1]
Hi, I want to fork your repository and redistribute my implementation version on github. But I didn't find a license in your repository. So I am confused what right you want to grant others. Could you please add a license in your repository, so that I can understand whether your repository can be forked and redistributed. Thanks a lot.

**Comment by jalused** [comment]
Thanks a lot for the license.

**Comment by wanghao2020** [comment]
Firstly, I am happy you find my code , this code for the five Chess is the
first version that just simply realize my idea. Certainly,there are lots of
problems in my code. I recently modify my code framework and write the
document . I hope you follow the next code version. Lastly, you can fork my
code and do what you want !

Good wishes!

Hao

2016-04-17 15:25 GMT+08:00 Liang Jiang notifications@github.com:
